name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    uses: Datadog/action-prebuildify/.github/workflows/build.yml@main
    with:
      package-manager: 'npm'
      cache: false
      min-node-version: 16
      napi: true
