name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    uses: Datadog/action-prebuildify/.github/workflows/build.yml@d4e89247e6dd34f485c0f92c12f0cc739c2f8c92 # main
    with:
      package-manager: 'npm'
      cache: false
      min-node-version: 16
      napi: true
